# Permalinks
permalink:           pretty

# Setup
title:               老洪发车公告板
tagline:             关于发车信息、新手教程、地址信息。
url:                 http://liujun3712.github.io
baseurl:             /DriversGroup
analytics_id:

# Owner/author information
owner:
  name:           Mr. Hong
  avatar:         avatar.png
  bio:            "Designer."



# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 6
paginate_path: "blog/page:num"


# Gems
plugins: [jekyll-paginate]

# Markdown 解释器
#markdown: redcarpet
#redcarpet:
#    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

markdown: kramdown
kramdown:
  input: GFM
